In [1]:
import numpy as np
from scipy.io import loadmat
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.pyplot import cm
import matplotlib as mpl
import cv2
import computer_vision as cv
from icecream import ic
from tqdm import trange
from numba import njit

%load_ext snakeviz
# %matplotlib inline
%matplotlib qt
%config InlineBackend.figure_format = 'retina'
from matplotlib import rc
rc('font', **{'family': 'serif', 'serif': ['Computer Modern']})
rc('text', usetex=True)

In [2]:
def compute_RMS_error(D1, D2):
    e_rms = np.sqrt(np.sum(D1**2 + D2**2) / (2*np.size(D1, 0)))
    return e_rms

In [3]:
def plot_lines_points_and_image(img_pts, img, l, path, save=False):

    fig = plt.figure(figsize=(8,6))
    ax = plt.axes()
    
    cv.compute_and_plot_lines(l, img, ax)
    ax.plot(img_pts[0], img_pts[1], 'o', color='blue', label='Random points')
    ax.set_xlabel('$x$')
    ax.set_ylabel('$y$')
    # plt.gca().invert_yaxis()
    # ax.invert_yaxis()
    ax.set_aspect('equal')
    ax.legend(loc="upper right")
    # ax.margins(x=0.1, y=0.1) 
    # fig.tight_layout()

    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    if save:
        fig.savefig(path, dpi=300)
    plt.show()


In [4]:
def plot_histogram(data, path, mean, save=False):
    fig = plt.figure()
    plt.hist(data, bins=100, color='tab:blue')
    plt.axvline(mean, linestyle='--', color='red', label='Mean: {}'.format(round(mean, 2)))
    plt.xlabel('Error')
    plt.ylabel('Frequency')
    # plt.xlim([0,70])
    plt.legend(loc="upper right")
    fig.tight_layout()
    if save:
        fig.savefig(path, dpi=300)
    plt.show()

In [5]:
def compute_point_line_distance_2D(l, p):
    # a = l[0,:]
    # b = l[1,:]
    # c = l[2,:]

    # x = p[0,:]
    # y = p[1,:]

    # D = np.abs(a*x + b*y + c) / (a**2 + b**2)**0.5

    numerator = np.abs(np.einsum("ij, ij->j", p, l))
    denominator = np.linalg.norm(l[:-1], axis=0)
    D = numerator / denominator

    return D

def compute_epipolar_lines(F, x1, x2):
    # l3 = F @ x1
    # l4 = F.T @ x2

    l2 = np.einsum("ij,jk->ik", F, x1)
    l1 = np.einsum("ji,jk->ik", F, x2)
    return l1, l2

def compute_epipolar_errors(F, x1, x2):
    l1, l2 = compute_epipolar_lines(F, x1, x2)
    D1 = compute_point_line_distance_2D(l1, x1)
    D2 = compute_point_line_distance_2D(l2, x2)
    return D1, D2

In [9]:
# @njit()
def estimate_E_robust(K, x1_norm, x2_norm):
    
    err_threshold_px = 2
    err_threshold = err_threshold_px / K[0,0]
    
    # alpha = 0.95
    # E = cv.estimate_E_DLT(x1_norm, x2_norm, enforce=True, verbose=False)
    # D1, D2, _ = cv.compute_epipolar_errors(E, x1_norm, x2_norm)
    # inliers = ((D1**2 + D2**2) / 2) < err_threshold**2
    # epsilon = np.sum(inliers) / np.size(inliers)
    # s = 8
    # T = np.ceil(np.log(1-alpha) / np.log(1-epsilon**s))

    s = 8

    best_inliers = None
    best_E = None
    max_inliers = 0

    for t in trange(10000):

        rand_mask = np.random.choice(np.size(x1_norm,1), s, replace=False)
        E = cv.estimate_E_DLT(x1_norm[:,rand_mask], x2_norm[:,rand_mask], enforce=True, verbose=False)

        D1, D2 = cv.compute_epipolar_errors(E, x1_norm, x2_norm)
        inliers = ((D1**2 + D2**2) / 2) < err_threshold**2

        n_inliers = np.sum(inliers)

        if n_inliers > max_inliers:
            best_inliers = np.copy(inliers)
            best_E = np.copy(E)
            max_inliers = n_inliers

            print(np.sum(inliers), end='\r')
        
    return best_E, best_inliers

In [14]:
path = r'C:\Users\erikn\skola\EEN020-Computer-Vision\assignment-4'
data = r'\data-2023\data'
compex = r'\compEx1data.mat'
img1 = r'\round_church1.jpg'
img2 = r'\round_church2.jpg'
report = r'\report-images'

round_church1 = cv.load_image(path+data+img1)
round_church2 = cv.load_image(path+data+img2)
K = cv.convert_mat_to_np(path+data+compex, 'K')
K_inv = np.linalg.inv(K)
x = cv.convert_mat_to_np(path+data+compex, 'x')
x1 = cv.dehomogenize(x[0,0])
x2 = cv.dehomogenize(x[0,1])

ransac = False
plt_pts = True
plt_hist = True
save = True
snakeviz = False

x1_norm = cv.transform_and_dehomogenize(K_inv, x1)
x2_norm = cv.transform_and_dehomogenize(K_inv, x2)

In [15]:
if ransac:
    E, inliers = estimate_E_robust(K, x1_norm, x2_norm)
    np.save(path+data+'/E_robust_ce1_4.npy', E)
    np.save(path+data+'/inliers_ce1_4.npy', inliers)
    print('No. inliers:', np.sum(inliers))
elif snakeviz:
    %snakeviz estimate_E_robust(K, x1_norm, x2_norm)
else:
    E = cv.estimate_E_DLT(x1_norm, x2_norm, enforce=True, verbose=False)


In [16]:
if ransac:
    E = np.load(path+data+'/E_robust_ce1_4.npy')
inliers = np.load(path+data+'/inliers_ce1_4.npy')
F = cv.convert_E_to_F(E, K, K)

print('\nE:', E)
print('F:', F)



# All points
D1, D2 = cv.compute_epipolar_errors(F, x1, x2)
e_rms = compute_RMS_error(D1, D2)

print('\nAll points:')
print('Ransac:', ransac)
print('Mean distance 1:', np.mean(D1))
print('Mean distance 2:', np.mean(D2))
print('RMS error:', e_rms)

path1 = path+report+'/CE1_hist1_ransac={}_all_points3.png'.format(ransac)
path2 = path+report+'/CE1_hist2_ransac={}_all_points3.png'.format(ransac)

if plt_hist:
    plot_histogram(D1, path1, np.mean(D1), save)
    plot_histogram(D2, path2, np.mean(D2), save)



# Inliers
D1, D2 = cv.compute_epipolar_errors(F, x1[:,inliers], x2[:,inliers])
e_rms = compute_RMS_error(D1, D2)

print('\nInliers:')
print('Ransac:', ransac)
print('Mean distance 1:', np.mean(D1))
print('Mean distance 2:', np.mean(D2))
print('RMS error:', e_rms)
print('No. inliers:', np.sum(inliers))

path1 = path+report+'/CE1_hist1_ransac={}_inliers3.png'.format(ransac)
path2 = path+report+'/CE1_hist2_ransac={}_inliers3.png'.format(ransac)

if plt_hist:
    plot_histogram(D1, path1, np.mean(D1), save)
    plot_histogram(D2, path2, np.mean(D2), save)



# Plot
if ransac:
    x1_norm = x1_norm[:,inliers]
    x2_norm = x2_norm[:,inliers]
    x1 = x1[:,inliers]
    x2 = x2[:,inliers]

rand_mask = np.random.choice(np.size(x2_norm,1), 20, replace=False)
x1_rand = x1[:,rand_mask]
x2_rand = x2[:,rand_mask]
l1, l2 = cv.compute_epipolar_lines(F, x1_rand, x2_rand)

path1 = path+report+'/CE1_round_church1_ransac={}_3.png'.format(ransac)
path2 = path+report+'/CE1_round_church2_ransac={}_3.png'.format(ransac)

if plt_pts:
    plot_lines_points_and_image(x1_rand, round_church1, l1, path1, save)
    plot_lines_points_and_image(x2_rand, round_church2, l2, path2, save)


E: [[-4.10093405e+02 -1.58910836e+04  1.57240861e+02]
 [ 1.58713700e+04 -4.01510925e+02  8.12819868e+02]
 [ 7.70039506e+00 -5.42253159e+01  1.00000000e+00]]
F: [[ 2.02278295e-07  7.82464842e-06 -5.29022579e-03]
 [-7.81494161e-06  1.97357443e-07  6.20439687e-03]
 [ 4.71216083e-03 -7.35563666e-03  1.00000000e+00]]

All points:
Ransac: False
Mean distance 1: 61.33360616690827
Mean distance 2: 63.46892741628846
RMS error: 155.95832290161417

Inliers:
Ransac: False
Mean distance 1: 16.405076850386244
Mean distance 2: 17.255170603651873
RMS error: 24.840289353844906
No. inliers: 5808


In [ ]:
# All points:
# Ransac: False
# Mean distance 1: 61.33360616690827
# Mean distance 2: 63.46892741628846
# RMS error: 155.95832290161417

# Inliers:
# Ransac: False
# Mean distance 1: 16.405076850386244
# Mean distance 2: 17.255170603651873
# RMS error: 24.840289353844906
# No. inliers: 5808

# All points:
# Ransac: True
# Mean distance 1: 58.218871126293756
# Mean distance 2: 71.45505427055761
# RMS error: 211.08275098532155

# Inliers:
# Ransac: True
# Mean distance 1: 0.2689665486285598
# Mean distance 2: 0.30710082051218507
# RMS error: 0.377877330889468
# No. inliers: 5808

In [ ]:
# All points:
# Ransac: False
# Mean distance 1: 61.33360616690827
# Mean distance 2: 63.46892741628846
# RMS error: 155.95832290161417

# Inliers:
# Ransac: False
# Mean distance 1: 16.32433861110083
# Mean distance 2: 17.191502221620578
# RMS error: 24.27603402567065
# No. inliers: 5800

# All points:
# Ransac: True
# Mean distance 1: 58.19428197281155
# Mean distance 2: 71.05765772253119
# RMS error: 209.48707355239185

# Inliers:
# Ransac: True
# Mean distance 1: 0.48506126307954056
# Mean distance 2: 0.5475310350564631
# RMS error: 0.6064325634663701
# No. inliers: 5800

In [ ]:
# All points:
# Ransac: False
# Mean distance 1: 61.33360616690827
# Mean distance 2: 63.46892741628846
# RMS error: 155.95832290161417

# Inliers:
# Ransac: False
# Mean distance 1: 14.527720653307188
# Mean distance 2: 15.349401111343274
# RMS error: 21.875573131094626
# No. inliers: 5231

# All points:
# Ransac: True
# Mean distance 1: 58.74538197965829
# Mean distance 2: 71.52507914842866
# RMS error: 209.63596816010937

# Inliers:
# Ransac: True
# Mean distance 1: 0.8859416907684401
# Mean distance 2: 1.0020265668647925
# RMS error: 1.084528021008188
# No. inliers: 5231