In [42]:
from sympy import Matrix, symbols
import numpy as np

F = np.array([[0,1,1],[2,0,4],[0,1,1]])
P1 = np.concatenate((np.eye(3), np.zeros(3)[:,np.newaxis]), 1)


U, S, VT = np.linalg.svd(F.T, full_matrices=False)
e_2 = VT[-1,:] / VT[-1,-1]
print(F.T @ e_2, e_2)
FT = Matrix(F.T)
print(FT.nullspace()[0])



e1, e2, e3 = symbols('e1 e2 e3')
e = Matrix([e1,e2,e3])
values = {e1: e_2[0], e2: e_2[1], e3: e_2[2]}
ex = Matrix([[0,-e3,e2],[e3,0,-e1],[-e2,e1,0]]).subs(values)
exF = ex*F
exFe = exF.row_join(e).subs(values)
P2 = np.array(exFe, dtype=float)
print(P2)



X1 = np.array([0,3,1,1])
X2 = np.array([-1,2,0,1])

x1 = P1 @ X1
x2 = P2 @ X1

x1 = x1/x1[-1]
x2 = x2/x2[-1]

print(x1, x2)
print(x2.T @ F @ x1)


x1 = P1 @ X2
x2 = P2 @ X2

x1 = x1
x2 = x2/x2[-1]

print(x1, x2)
print(x2.T @ F @ x1)

F = ex @ P2[:,:-1]
F/F[-1,-1]

F = np.array([[0,1,1],[2,0,4],[0,1,1]])
U, S, VT = np.linalg.svd(F, full_matrices=False)
e_1 = VT[-1,:] / VT[-1,-1]
print(F @ e_1, e_1)
F = Matrix(F.T)
print(F*F.nullspace()[0], F.nullspace()[0])

[ 3.14018492e-16 -2.22044605e-16  4.05992379e-16] [-1.00000000e+00  1.57009246e-16  1.00000000e+00]
Matrix([[-1], [0], [1]])
[[-2.00000000e+00  1.57009246e-16 -4.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.00000000e+00  2.00000000e+00  1.57009246e-16]
 [-2.00000000e+00 -1.57009246e-16 -4.00000000e+00  1.00000000e+00]]
[0. 3. 1.] [ 1.66666667 -2.66666667  1.        ]
1.7763568394002505e-15
[-1.  2.  0.] [0.33333333 1.33333333 1.        ]
0.0
[-2.22044605e-16 -8.88178420e-16 -2.22044605e-16] [-2. -1.  1.]
Matrix([[0], [0], [0]]) Matrix([[-1], [0], [1]])
