In [1]:
import numpy as np
from scipy.io import loadmat
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib as mpl
import cv2

# %matplotlib inline
%matplotlib qt

%config InlineBackend.figure_format = 'retina'

In [2]:
def load_images():    
    path1 = r'C:\Users\erikn\skola\EEN020-Computer-Vision\assignment-1\A1data\data\compEx3img1.jpg'
    path2 = r'C:\Users\erikn\skola\EEN020-Computer-Vision\assignment-1\A1data\data\compEx3img2.jpg'
    return cv2.imread(path1), cv2.imread(path2)

In [3]:
def mat_to_np():    
    path = r'C:\Users\erikn\skola\EEN020-Computer-Vision\assignment-1\A1data\data\compEx3.mat'
    mat_data = loadmat(path)
    P1 = np.array(mat_data['P1'])
    P2 = np.array(mat_data['P2'])
    U = np.array(mat_data['U'])
    return P1, P2, U

In [4]:
def to_cart(x):
    return x[:-1]/x[-1]

In [5]:
def normalize(v):
    return v/(v @ v)**0.5

In [6]:
def compute_camera_center(P):
    M = P[:,:3]
    P4 = P[:,-1]
    C = -1*(np.linalg.inv(M) @ P4)
    print(C)
    return C

In [7]:
def compute_principal_axis(P):
    M = P[:,:3]
    m3 = P[-1,:3]
    v = np.linalg.det(M) * m3
    return normalize(v)

In [8]:
def camera_center_and_axis(P):
    C = compute_camera_center(P)
    p_axis = compute_principal_axis(P) 
    return C, p_axis

In [9]:
def plot_camera(P1, P2, s1, s2, U):
    C1, p_axis1 = camera_center_and_axis(P1)
    C2, p_axis2 = camera_center_and_axis(P2)
    # p_axis2 = P2[-1,:3]

    fig1 = plt.figure(figsize=(10,8))
    ax = plt.axes(projection='3d')
    ax.plot(U[0], U[1], U[2], '.', ms=0.2, color='magenta', label='U')
    
    ax.plot(C1[0], C1[1], C1[2], 'o', color='red', label='Camera center 1')
    ax.plot(C2[0], C2[1], C2[2], 'o', color='lime', label='Camera center 2')

    x_p_axis1 = C1[0] + s1*p_axis1[0]
    y_p_axis1 = C1[1] + s1*p_axis1[1]
    z_p_axis1 = C1[2] + s1*p_axis1[2]

    x_p_axis2 = C2[0] + s2*p_axis2[0]
    y_p_axis2 = C2[1] + s2*p_axis2[1]
    z_p_axis2 = C2[2] + s2*p_axis2[2]

    ax.plot(x_p_axis1, y_p_axis1, z_p_axis1, 'o', color='blue', label='$s_1\\cdot$Principal axis 1')
    ax.plot(x_p_axis2, y_p_axis2, z_p_axis2, 'o', color='cyan', label='$s_2\\cdot$Principal axis 2')

    ax.plot([x_p_axis1,C1[0]], [y_p_axis1,C1[1]], [z_p_axis1,C1[2]], '-', color='black')
    ax.plot([x_p_axis2,C2[0]], [y_p_axis2,C2[1]], [z_p_axis2,C2[2]], '-', color='black')

    plt.legend(loc="lower right")
    plt.show()
    

In [10]:
img1, img2 = load_images()
P1, P2, U = mat_to_np()
C1, p_axis1 = camera_center_and_axis(P1)
C2, p_axis2 = camera_center_and_axis(P2)

print(P1 @ np.append(C1,1))
print(P2 @ np.append(C2,1), '\n')

print('Camera center 1:', C1, '\nPrincipal axis 1:', p_axis1)
print('\nCamera center 2:', C2, '\nPrincipal axis 2:', p_axis2)

s1 = 22
s2 = 18
print(P1,'\n',P2)
plot_camera(P1, P2, s1, s2, to_cart(U))

[-0. -0. -0.]
[  6.6352039   14.84597919 -15.06911585]
[0. 0. 0.]
[0.00000000e+00 7.27595761e-12 0.00000000e+00] 

Camera center 1: [-0. -0. -0.] 
Principal axis 1: [0.31292281 0.94608467 0.08368463]

Camera center 2: [  6.6352039   14.84597919 -15.06911585] 
Principal axis 2: [0.03186384 0.34016542 0.93982561]
[[ 2.35362471e+03  1.16524276e+02  1.02333589e+03  0.00000000e+00]
 [ 1.15667754e+03  4.70914434e+02 -2.14150090e+03  0.00000000e+00]
 [ 3.12922811e-01  9.46084667e-01  8.36846335e-02  0.00000000e+00]] 
 [[ 2.39824255e+03 -2.78991933e+01  9.20867956e+02 -1.62197157e+03]
 [ 3.60077547e+02  2.44217303e+03 -2.27649962e+02 -4.20761215e+04]
 [ 3.18638435e-02  3.40165417e-01  9.39825614e-01  8.90082925e+00]]
[-0. -0. -0.]
[  6.6352039   14.84597919 -15.06911585]
